server:
  port: 8206
mybatis-plus:
  mapper-locations: classpath:mapper/*Mapper.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://39.106.95.229:3306/gmall_product?createDatabaseIfNotExist=true&useSSL=false&charactorEncoding=utf8
  redis:
    host: 39.106.95.229
    password:
    database: 0
    port: 6379
  zipkin:
    base-url: http://39.106.95.229:9411
  rabbitmq:
    host: 39.106.95.229
    port: 5672
    username: guest
    password: guest
